name: "Hello world workflow"

# controols when the action will run . Triggers the workflow on push some to master or the production branch
on:
    push:
        branches:
            - master
            - production
jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "Print hello world"
              run: echo "Hello world"