name: "Multi event pipeline"
on:
    push: # Event: Whenever a push is made to the repositry as on the master branch
        branches:
            - master
            - test
    pull_request: # Event: Whenever a pull request is made to the repositry
        branches:
            - master
                        
         
jobs:
    on-push:
        if: github.event == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master push" #step1
              run: echo "Running on master branch"
    on-pull-request: #Job name
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on pull request" #step1
              run: echo "Running on pull request"
    on-workflow-dispatch: #Job 
        if: github.event == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on workflow dispatch" #step1
              run: echo "Running on workflow dispatch"